### List users
GET http://localhost:3000/users

### Get user
GET http://localhost:3000/users/5

### Create user
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Atila",
    "email": "Atila@Atila.com",
    "password": "Atila1234"
}

### Update user
PATCH http://localhost:3000/users/3
Content-Type: application/json

{
    "name": "Rafa",
    "email": "rafa@rafa.com",
    "password": "rafa"
}

### Update user
DELETE http://localhost:3000/users/5